

        name: Hourly Crypto Scanner

on:
  schedule:
    - cron: '0 * * * *'  # every hour at 0 minutes
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run Scanner
      run: python EMA_Scanner.py
