name: Hourly Crypto Scanner

on:
  schedule:
    - cron: '25 * * * *'  # every hour at minute 30
  workflow_dispatch:

permissions:
  contents: write   # required for pushing changes

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4   # v4 is the latest

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run Scanner
      run: python RSI_Buy_Sell.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Commit Watchlist Updates
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add buy_watchlist.json sell_watchlist.json Supertrend_buy_watchlist.json Supertrend_sell_watchlist.json|| true
        git commit -m "Update watchlists [skip ci]" || echo "No changes to commit"
        git push
